[zimbra]
mail01 ansible_host=192.168.7.25 ansible_user=root

[zimbra:vars]
zimbra_fqdn=zimbra10.dwinar.web.id
zimbra_domain=dwinar.web.id
zimbra_timezone=Asia/Jakarta
zimbra_admin_user=admin
zimbra_admin_password=rahasia
